<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVuNTQkf\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVuNTQkf/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVuNTQkf.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVuNTQkf\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerVuNTQkf\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'VuNTQkf',
    'container.build_id' => 'd726b18b',
    'container.build_time' => 1614808049,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVuNTQkf');
